resource "aws_ecs_cluster" "this" {
  name = var.name

  setting {
    name  = "containerInsights"
    value = "enabled"
  }

  tags = var.tags
}

resource "aws_cloudwatch_log_group" "app" {
  name              = "/ecs/${var.name}"
  retention_in_days = var.log_retention_days
  tags              = var.tags
}

# Only created when a license key is supplied — see variables.tf. Same
# pattern as modules/rds's DB secrets, except this value comes from the
# caller rather than being generated by Terraform.
resource "aws_secretsmanager_secret" "new_relic_license_key" {
  count = var.new_relic_license_key != null ? 1 : 0
  name  = "ark-fund-api/${var.environment}/new-relic-license-key"
  tags  = var.tags
}

resource "aws_secretsmanager_secret_version" "new_relic_license_key" {
  count         = var.new_relic_license_key != null ? 1 : 0
  secret_id     = aws_secretsmanager_secret.new_relic_license_key[0].id
  secret_string = var.new_relic_license_key
}

locals {
  # Bundled in every image regardless (see Dockerfile), but only actually
  # loaded when JAVA_TOOL_OPTIONS points at it — which only happens when a
  # license key was supplied. Local dev / any environment without a key sees
  # none of this.
  new_relic_environment = var.new_relic_license_key != null ? [
    { name = "NEW_RELIC_APP_NAME", value = coalesce(var.new_relic_app_name, var.name) },
    { name = "NEW_RELIC_LOG", value = "stdout" }, # the agent's OWN diagnostic log, not app log forwarding
    { name = "JAVA_TOOL_OPTIONS", value = "-javaagent:/app/newrelic/newrelic.jar" },
    # Explicit, not relying on the agent version's default: forwards this
    # app's own SLF4J/Logback lines (ClientController, ClientService, etc.)
    # into New Relic's Logs UI, decorated with trace.id/span.id so each line
    # links back to the request that produced it — distinct from APM
    # traces/metrics, which flow regardless of this setting.
    { name = "NEW_RELIC_APPLICATION_LOGGING_ENABLED", value = "true" },
    { name = "NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED", value = "true" },
  ] : []

  new_relic_secrets = var.new_relic_license_key != null ? [
    { name = "NEW_RELIC_LICENSE_KEY", valueFrom = aws_secretsmanager_secret.new_relic_license_key[0].arn },
  ] : []
}

resource "aws_ecs_task_definition" "app" {
  family                   = var.name
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = var.cpu
  memory                   = var.memory
  execution_role_arn       = aws_iam_role.execution.arn
  task_role_arn            = aws_iam_role.task.arn

  # Graviton (ARM64) — about 20% cheaper per vCPU-hour than the X86_64
  # default, and eclipse-temurin/maven are multi-arch, so the build image
  # needs no changes. Also means an Apple Silicon Mac builds a native image
  # here instead of needing --platform linux/amd64 emulation.
  runtime_platform {
    cpu_architecture        = "ARM64"
    operating_system_family = "LINUX"
  }

  # Mirrors deploy/ecs/task-definition.*.json exactly — those files are the
  # break-glass path (docs/12-AWS-Deployment.md §5) for registering a task
  # definition by hand when CI/CD is unavailable; this is the same shape,
  # generated so the two never drift apart silently.
  container_definitions = jsonencode([
    {
      name      = "ark-fund-api"
      image     = "${var.ecr_repository_url}:${var.image_tag}"
      essential = true
      portMappings = [
        { containerPort = var.container_port, protocol = "tcp" }
      ]
      environment = concat([
        { name = "SPRING_PROFILES_ACTIVE", value = var.environment },
        { name = "AWS_REGION", value = var.aws_region },
      ], local.new_relic_environment)
      secrets = concat([
        { name = "SPRING_DATASOURCE_URL", valueFrom = var.db_url_secret_arn },
        { name = "SPRING_DATASOURCE_USERNAME", valueFrom = var.db_username_secret_arn },
        { name = "SPRING_DATASOURCE_PASSWORD", valueFrom = var.db_password_secret_arn },
      ], local.new_relic_secrets)
      healthCheck = {
        command  = ["CMD-SHELL", "curl -f http://localhost:${var.container_port}/actuator/health || exit 1"]
        interval = 15
        timeout  = 5
        retries  = 3
        # 180s, matching health_check_grace_period_seconds below — a plain
        # Spring Boot startup would be comfortable with far less, but with
        # the New Relic agent active, its bytecode instrumentation at
        # premain is CPU-bound and measured at ~105-125s wall clock on this
        # task's 0.5 vCPU. This is the container's own internal check
        # (curl from inside the container, no ALB/network involved) — it
        # will kill the task on its own if too short, independent of the
        # ALB-driven grace period above.
        startPeriod = 180
      }
      logConfiguration = {
        logDriver = "awslogs"
        options = {
          "awslogs-group"         = aws_cloudwatch_log_group.app.name
          "awslogs-region"        = var.aws_region
          "awslogs-stream-prefix" = "app"
        }
      }
    }
  ])

  tags = var.tags
}

resource "aws_ecs_service" "app" {
  name            = var.name
  cluster         = aws_ecs_cluster.this.id
  task_definition = aws_ecs_task_definition.app.arn
  desired_count   = var.desired_count
  launch_type     = "FARGATE"

  network_configuration {
    subnets          = var.private_subnet_ids
    security_groups  = [var.security_group_id]
    assign_public_ip = false # private subnets only — see modules/network
  }

  load_balancer {
    target_group_arn = var.target_group_arn
    container_name   = "ark-fund-api"
    container_port   = var.container_port
  }

  # Without this, ALB health-check failures count against a task from the
  # instant it registers — zero tolerance for how long Spring Boot actually
  # takes to start (cold JVM, Hibernate metamodel, Tomcat, and — when
  # enabled — the New Relic agent's own bytecode instrumentation at premain,
  # which adds real time on top of a plain boot). Without a grace period, a
  # perfectly healthy task can get killed mid-startup, loop forever through
  # deployment attempts that never succeed, and the deployment circuit
  # breaker above never even gets a clean run to judge.
  health_check_grace_period_seconds = var.health_check_grace_period_seconds

  deployment_circuit_breaker {
    enable   = true
    rollback = true
  }

  # CI/CD (.github/workflows/ci-cd.yml) registers new task definition
  # revisions and updates the service directly as part of the deploy
  # pipeline — a `terraform apply` run between deploys must not revert
  # today's running revision back to whatever image_tag was last known here.
  # Terraform still owns everything else about the service (cluster,
  # subnets, target group, autoscaling); only the specific task definition
  # in flight is CI's responsibility day to day.
  #
  # Production's blue/green rollout via CodeDeploy (docs/05-CICD.md §3,
  # deploy/ecs/appspec.yaml) is a deliberate follow-up on top of this
  # module, not yet wired into Terraform — this service resource gives you
  # a plain ECS rolling-update service in both environments today.
  lifecycle {
    ignore_changes = [task_definition, desired_count]
  }

  tags = var.tags
}