-- Schema for the Ark investment management API.
-- Written in portable SQL so the same migrations apply to PostgreSQL (runtime)
-- and H2 in PostgreSQL mode (tests). UUIDs are generated by the application
-- rather than the database to keep this portable and to let the service layer
-- know an entity's identity before it is persisted.

CREATE TABLE clients (
    id          UUID          PRIMARY KEY,
    name        VARCHAR(200)  NOT NULL,
    email       VARCHAR(320)  NOT NULL,
    created_at  TIMESTAMP     NOT NULL,
    updated_at  TIMESTAMP     NOT NULL,
    CONSTRAINT uq_clients_email UNIQUE (email)
);

CREATE TABLE funds (
    id              UUID          PRIMARY KEY,
    client_id       UUID          NOT NULL,
    name            VARCHAR(200)  NOT NULL,
    description     VARCHAR(1000),
    inception_date  DATE          NOT NULL,
    created_at      TIMESTAMP     NOT NULL,
    updated_at      TIMESTAMP     NOT NULL,
    CONSTRAINT fk_funds_client FOREIGN KEY (client_id) REFERENCES clients (id),
    -- Fund names only need to be unique within a client, not globally: two
    -- unrelated clients may each legitimately run a fund called "Growth Fund I".
    CONSTRAINT uq_funds_client_name UNIQUE (client_id, name)
);

CREATE TABLE investors (
    id          UUID          PRIMARY KEY,
    client_id   UUID          NOT NULL,
    name        VARCHAR(200)  NOT NULL,
    email       VARCHAR(320)  NOT NULL,
    created_at  TIMESTAMP     NOT NULL,
    updated_at  TIMESTAMP     NOT NULL,
    CONSTRAINT fk_investors_client FOREIGN KEY (client_id) REFERENCES clients (id),
    CONSTRAINT uq_investors_client_email UNIQUE (client_id, email)
);

CREATE TABLE transactions (
    id                UUID           PRIMARY KEY,
    -- client_id is denormalised onto the transaction deliberately. Every query
    -- in a multi-tenant system is tenant-scoped, and carrying the tenant here
    -- avoids joining through fund or investor on the hottest table in the schema.
    client_id         UUID           NOT NULL,
    fund_id           UUID           NOT NULL,
    investor_id       UUID           NOT NULL,
    type              VARCHAR(40)    NOT NULL,
    -- Amounts are always stored positive; whether a transaction adds to or
    -- subtracts from a fund is derived from its type (see TransactionType).
    -- Storing signed amounts would make the sign and the type two sources of
    -- truth that can disagree.
    amount            NUMERIC(19, 2) NOT NULL,
    transaction_date  DATE           NOT NULL,
    notes             VARCHAR(1000),
    created_at        TIMESTAMP      NOT NULL,
    updated_at        TIMESTAMP      NOT NULL,
    CONSTRAINT fk_transactions_client   FOREIGN KEY (client_id)   REFERENCES clients (id),
    CONSTRAINT fk_transactions_fund     FOREIGN KEY (fund_id)     REFERENCES funds (id),
    CONSTRAINT fk_transactions_investor FOREIGN KEY (investor_id) REFERENCES investors (id),
    CONSTRAINT ck_transactions_amount_positive CHECK (amount > 0)
);

-- Reporting reads dominate this table: fund/investor rollups and date-bounded
-- "as of" queries are the two access patterns these indexes serve.
CREATE INDEX idx_transactions_fund_date     ON transactions (fund_id, transaction_date);
CREATE INDEX idx_transactions_investor_date ON transactions (investor_id, transaction_date);
CREATE INDEX idx_transactions_client_date   ON transactions (client_id, transaction_date);
